# Use an official Python image as the base
FROM python:3.9-slim

# Install system dependencies for building dlib/face_recognition
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        libopenblas-dev \
        liblapack-dev \
        libx11-dev \
        python3-dev \
        && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1

# Default settings — override via -e (or Synology Container Manager Environment tab)
ENV REFERENCE_FOLDER=/app/reference_photos
ENV PHOTO_FOLDER=/app/photo_folder
ENV OUTPUT_FOLDER=/app/similar_photos
ENV SIMILARITY_THRESHOLD=0.5
ENV DATE_RANGE_START=
ENV DATE_RANGE_END=
ENV NEIGHBOR_WINDOW=20
ENV NEIGHBOR_SIZE_RATIO=0.5
# WORKERS unset → defaults to cpu_count() at runtime. Set explicitly to tune.
ENV WORKERS=
# Regex(es) to skip by filename. Default catches 4K Stogram (Instagram archive) files.
ENV SKIP_FILENAME_PATTERNS=^FILE\\d+\\.JPG$
# Filename skip only triggers if the file is <= this many bytes (real camera
# photos are always larger). Protects EaseUS-recovered photos sharing the
# FILE<num>.JPG naming pattern. Set 0 to disable size guard (dangerous).
ENV SKIP_FILENAME_MAX_SIZE=500000
# Pre-computed reference encodings pickle (generated by crop_references.py).
# If set and the file exists, references are loaded from this instead of
# re-encoded each run. Recommended for the best recall: lets you manually
# crop tricky reference faces once and reuse the encodings.
ENV REFERENCE_PICKLE=
# Comma-separated EXIF SerialNumbers. If set, files with EXIF SerialNumber
# not in this set are skipped. Files with no EXIF serial pass through.
# Useful for restricting to "shot by him" when the source drive has many
# other photographers' files.
ENV EXIF_SERIAL_FILTER=
# SQLite cache path. Re-runs after tweaks (threshold, references) skip the
# face encoding step for already-processed files. Empty to disable.
ENV CACHE_PATH=/app/similar_photos/.cache/encodings.db

# Set work directory
WORKDIR /app

# Copy requirements.txt if you have one, else install directly
COPY requirements.txt ./

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Copy your code into the container
COPY . .

# Default command (can be overridden)
CMD ["python", "find_photos.py"]
